name: Deploy Cloud Transcoder to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
            DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            EC2_USER: ${{ secrets.EC2_USER }}
            EC2_HOST: ${{ secrets.EC2_HOST }}
            IMAGE_TAG: ${{ github.sha }}

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
            
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}
            
            -   name: Docker login
                run: |
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $CONTAINER_REGISTRY
            
            -   name: Build & Push Image to Docker Hub
                run: |
                    docker build -t $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:$IMAGE_TAG .
                    docker push $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:$IMAGE_TAG

                    docker tag $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:$IMAGE_TAG $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:latest
                    docker push $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:latest
                    
            -   name: Setup SSH
                run: |
                    mkdir -p ~/.ssh
                    cat <<EOF > ~/.ssh/id_ed25519
                    $SSH_PRIVATE_KEY
                    EOF
                    chmod 600 ~/.ssh/id_ed25519
                    ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts || true
                    scp deploy.sh $EC2_USER@$EC2_HOST:/home/ubuntu/deploy.sh
            
            
            -   name: Deploy To EC2
                run: |
                    ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_ed25519 $EC2_USER@$EC2_HOST <<EOF
                        chmod +x /home/ubuntu/deploy.sh

                        bash /home/ubuntu/deploy.sh $CONTAINER_REGISTRY/$DOCKER_IMAGE_NAME:$IMAGE_TAG

                        rm /home/ubuntu/deploy.sh
                    EOF